# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Income_Ui.ui'
#
# Created: Wed May 16 12:16:54 2012
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Income(object):
    def setupUi(self, Income):
        Income.setObjectName("Income")
        Income.resize(662, 531)
        self.label = QtGui.QLabel(Income)
        self.label.setGeometry(QtCore.QRect(10, 70, 131, 17))
        self.label.setObjectName("label")
        self.nameEdit = QtGui.QLineEdit(Income)
        self.nameEdit.setGeometry(QtCore.QRect(150, 60, 501, 27))
        self.nameEdit.setObjectName("nameEdit")
        self.label_2 = QtGui.QLabel(Income)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 131, 17))
        self.label_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(Income)
        self.label_3.setGeometry(QtCore.QRect(10, 150, 131, 17))
        self.label_3.setObjectName("label_3")
        self.measureBox = QtGui.QComboBox(Income)
        self.measureBox.setGeometry(QtCore.QRect(150, 140, 111, 27))
        self.measureBox.setEditable(True)
        self.measureBox.setObjectName("measureBox")
        self.label_4 = QtGui.QLabel(Income)
        self.label_4.setGeometry(QtCore.QRect(10, 190, 131, 17))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtGui.QLabel(Income)
        self.label_5.setGeometry(QtCore.QRect(10, 229, 131, 17))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtGui.QLabel(Income)
        self.label_6.setGeometry(QtCore.QRect(10, 270, 141, 17))
        self.label_6.setObjectName("label_6")
        self.countEdit = QtGui.QLineEdit(Income)
        self.countEdit.setGeometry(QtCore.QRect(150, 180, 113, 27))
        self.countEdit.setObjectName("countEdit")
        self.massEdit = QtGui.QLineEdit(Income)
        self.massEdit.setGeometry(QtCore.QRect(150, 220, 113, 27))
        self.massEdit.setObjectName("massEdit")
        self.priceEdit = QtGui.QLineEdit(Income)
        self.priceEdit.setGeometry(QtCore.QRect(150, 260, 113, 27))
        self.priceEdit.setObjectName("priceEdit")
        self.saveIncomButton = QtGui.QCommandLinkButton(Income)
        self.saveIncomButton.setGeometry(QtCore.QRect(10, 400, 186, 41))
        self.saveIncomButton.setObjectName("saveIncomButton")
        self.addProductButton = QtGui.QPushButton(Income)
        self.addProductButton.setGeometry(QtCore.QRect(536, 370, 111, 27))
        self.addProductButton.setObjectName("addProductButton")
        self.label_7 = QtGui.QLabel(Income)
        self.label_7.setGeometry(QtCore.QRect(10, 110, 131, 17))
        self.label_7.setObjectName("label_7")
        self.nomenclatureEdit = QtGui.QLineEdit(Income)
        self.nomenclatureEdit.setGeometry(QtCore.QRect(150, 100, 113, 27))
        self.nomenclatureEdit.setObjectName("nomenclatureEdit")
        self.productEdit = QtGui.QComboBox(Income)
        self.productEdit.setGeometry(QtCore.QRect(150, 20, 221, 27))
        self.productEdit.setEditable(True)
        self.productEdit.setInsertPolicy(QtGui.QComboBox.NoInsert)
        self.productEdit.setFrame(True)
        self.productEdit.setModelColumn(2)
        self.productEdit.setObjectName("productEdit")

        self.retranslateUi(Income)
        QtCore.QObject.connect(self.productEdit, QtCore.SIGNAL("editTextChanged(QString)"), self.nameEdit.setText)
        QtCore.QMetaObject.connectSlotsByName(Income)
        Income.setTabOrder(self.productEdit, self.nameEdit)
        Income.setTabOrder(self.nameEdit, self.nomenclatureEdit)
        Income.setTabOrder(self.nomenclatureEdit, self.measureBox)
        Income.setTabOrder(self.measureBox, self.countEdit)
        Income.setTabOrder(self.countEdit, self.massEdit)
        Income.setTabOrder(self.massEdit, self.priceEdit)
        Income.setTabOrder(self.priceEdit, self.saveIncomButton)
        Income.setTabOrder(self.saveIncomButton, self.addProductButton)

    def retranslateUi(self, Income):
        Income.setWindowTitle(QtGui.QApplication.translate("Income", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Income", "Наименование", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Income", "Продукт", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Income", "Ед. измерения", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Income", "Количество", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Income", "Масса на единицу", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Income", "Цена", None, QtGui.QApplication.UnicodeUTF8))
        self.saveIncomButton.setText(QtGui.QApplication.translate("Income", "Сохранить [F12]", None, QtGui.QApplication.UnicodeUTF8))
        self.addProductButton.setText(QtGui.QApplication.translate("Income", "Добавить [F9]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Income", "Номенклатурн. №", None, QtGui.QApplication.UnicodeUTF8))

