# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Menu_Ui.ui'
#
# Created: Wed Sep  5 17:46:11 2012
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Menu(object):
    def setupUi(self, Menu):
        Menu.setObjectName("Menu")
        Menu.resize(835, 563)
        self.gridLayout_2 = QtGui.QGridLayout(Menu)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtGui.QLabel(Menu)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit = QtGui.QLineEdit(Menu)
        self.lineEdit.setEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.pushButton_3 = QtGui.QPushButton(Menu)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_2.addWidget(self.pushButton_3, 0, 2, 1, 1)
        self.productBox = QtGui.QGroupBox(Menu)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.productBox.sizePolicy().hasHeightForWidth())
        self.productBox.setSizePolicy(sizePolicy)
        self.productBox.setFlat(False)
        self.productBox.setObjectName("productBox")
        self.productLayout = QtGui.QGridLayout(self.productBox)
        self.productLayout.setObjectName("productLayout")
        self.treeWidgetDish = QtGui.QTreeWidget(self.productBox)
        self.treeWidgetDish.setEnabled(True)
        self.treeWidgetDish.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.treeWidgetDish.setAlternatingRowColors(True)
        self.treeWidgetDish.setAutoExpandDelay(-1)
        self.treeWidgetDish.setObjectName("treeWidgetDish")
        self.productLayout.addWidget(self.treeWidgetDish, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.productBox, 1, 0, 1, 2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.addDishButton = QtGui.QPushButton(Menu)
        self.addDishButton.setObjectName("addDishButton")
        self.verticalLayout.addWidget(self.addDishButton)
        self.addToMenuButton = QtGui.QPushButton(Menu)
        self.addToMenuButton.setObjectName("addToMenuButton")
        self.verticalLayout.addWidget(self.addToMenuButton)
        self.gridLayout_2.addLayout(self.verticalLayout, 1, 2, 1, 1)
        self.menuBox = QtGui.QGroupBox(Menu)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menuBox.sizePolicy().hasHeightForWidth())
        self.menuBox.setSizePolicy(sizePolicy)
        self.menuBox.setAutoFillBackground(False)
        self.menuBox.setFlat(False)
        self.menuBox.setCheckable(False)
        self.menuBox.setObjectName("menuBox")
        self.gridLayout = QtGui.QGridLayout(self.menuBox)
        self.gridLayout.setObjectName("gridLayout")
        self.treeWidgetMenu = QtGui.QTreeWidget(self.menuBox)
        self.treeWidgetMenu.setEnabled(True)
        self.treeWidgetMenu.setObjectName("treeWidgetMenu")
        self.gridLayout.addWidget(self.treeWidgetMenu, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.menuBox, 2, 0, 1, 2)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.saveMenuButton = QtGui.QPushButton(Menu)
        self.saveMenuButton.setObjectName("saveMenuButton")
        self.verticalLayout_2.addWidget(self.saveMenuButton)
        self.delFromMenuButton = QtGui.QPushButton(Menu)
        self.delFromMenuButton.setObjectName("delFromMenuButton")
        self.verticalLayout_2.addWidget(self.delFromMenuButton)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 2, 2, 1, 1)

        self.retranslateUi(Menu)
        QtCore.QMetaObject.connectSlotsByName(Menu)
        Menu.setTabOrder(self.treeWidgetDish, self.treeWidgetMenu)
        Menu.setTabOrder(self.treeWidgetMenu, self.lineEdit)
        Menu.setTabOrder(self.lineEdit, self.addDishButton)
        Menu.setTabOrder(self.addDishButton, self.pushButton_3)

    def retranslateUi(self, Menu):
        Menu.setWindowTitle(QtGui.QApplication.translate("Menu", "Меню", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Menu", "Поиск", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("Menu", "Найти", None, QtGui.QApplication.UnicodeUTF8))
        self.productBox.setTitle(QtGui.QApplication.translate("Menu", "Блюда", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetDish.headerItem().setText(0, QtGui.QApplication.translate("Menu", "Наименование", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetDish.headerItem().setText(1, QtGui.QApplication.translate("Menu", "Количество", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetDish.headerItem().setText(2, QtGui.QApplication.translate("Menu", "Цена", None, QtGui.QApplication.UnicodeUTF8))
        self.addDishButton.setText(QtGui.QApplication.translate("Menu", "Добавить[F9]", None, QtGui.QApplication.UnicodeUTF8))
        self.addDishButton.setShortcut(QtGui.QApplication.translate("Menu", "F9", None, QtGui.QApplication.UnicodeUTF8))
        self.addToMenuButton.setText(QtGui.QApplication.translate("Menu", "Внести[Пробел]", None, QtGui.QApplication.UnicodeUTF8))
        self.addToMenuButton.setShortcut(QtGui.QApplication.translate("Menu", "Space", None, QtGui.QApplication.UnicodeUTF8))
        self.menuBox.setTitle(QtGui.QApplication.translate("Menu", "Меню", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetMenu.headerItem().setText(0, QtGui.QApplication.translate("Menu", "Наименование", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetMenu.headerItem().setText(1, QtGui.QApplication.translate("Menu", "Количество", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetMenu.headerItem().setText(2, QtGui.QApplication.translate("Menu", "Цена", None, QtGui.QApplication.UnicodeUTF8))
        self.saveMenuButton.setText(QtGui.QApplication.translate("Menu", "Сохранить[F12]", None, QtGui.QApplication.UnicodeUTF8))
        self.saveMenuButton.setShortcut(QtGui.QApplication.translate("Menu", "F12", None, QtGui.QApplication.UnicodeUTF8))
        self.delFromMenuButton.setText(QtGui.QApplication.translate("Menu", "Убрать[<--]", None, QtGui.QApplication.UnicodeUTF8))
        self.delFromMenuButton.setShortcut(QtGui.QApplication.translate("Menu", "Backspace", None, QtGui.QApplication.UnicodeUTF8))

